pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(Parameters.solution)'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(Parameters.solution)'

    platform: '$(BuildPlatform)'

    configuration: '$(BuildConfiguration)'

- task: VSTest@2
  displayName: 'Unit Tests'
  inputs:
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*Tests.dll
     !**\obj\**

    codeCoverageEnabled: true

    platform: '$(BuildPlatform)'

    configuration: '$(BuildConfiguration)'

- powershell: |
    $coverageFilePath = (Resolve-Path -path "$($Env:CoveragePath)*\*.coverage").Path
    Invoke-Expression '& $Env:CodeCoverage analyze /output:coverage.coveragexml "$($coverageFilePath)"'
    Invoke-Expression '& dotnet tool install coveralls.net --version 1.0.0 --tool-path coveralls.net'
    Invoke-Expression '& coveralls.net\csmacnz.Coveralls --dynamiccodecoverage -i coverage.coveragexml --commitId $Env:REPO_COMMIT --commitBranch $Env:REPO_BRANCH --commitMessage "$($Env:REPO_COMMIT_MESSAGE)" --jobId $env:JOB_ID --useRelativePaths -o cov.json'
    
  displayName: 'Publish to Coveralls.io'
  env: 
    CoveragePath: 'D:\a\1\s\TestResults\'
    CodeCoverage: $(CodeCoverage)
    COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN)
    REPO_COMMIT: $(Build.SourceVersion)
    REPO_BRANCH: master
    JOB_ID: $(Build.BuildId)
    REPO_COMMIT_MESSAGE: $(Build.SourceVersionMessage)
  workingDirectory: $(Agent.BuildDirectory)